version: "3.8"

services:
  pearn-server:
    container_name: "pearn-server"
    image: pearn_api
    build:
      context: "./../backend"
      dockerfile: "./Dockerfile"
    env_file: .env
    ports:
      - 5050:5050
    environment:
      - MONGO_CON_STRING=mongodb+srv://phungthanhtu:Phungthanhtu!1@cluster0.ylzeo0f.mongodb.net/pearn
      - ACCESS_TOKEN_SECRET=Iwlakjsklcjzklxjclksjdklasjdlksdjwkldjlaksjkjvkjveifjahwj
      - ACCESS_TOKEN_LIFE=400m
      - PORT=5050
    volumes:
      - ../backend:/backend
      - /backend/node_modules
    command: npm run dev
