version: "3.8"

services:
  mongo :
    container_name: "pearn-mongo-db"
    image: "mongo"
    env_file:
      - .env
    volumes:
      - ../database/mongo:/data/db
    ports:
      - "27018:27017"
  client:
    container_name: "pearn-client"
    volumes:
      - ../frontend:/frontend
      - /frontend/node_modules
    build:
      context: "./../frontend"
      dockerfile: "./Dockerfile"
    ports: 
      - 3000:3000
  server:
    container_name: "pearn-server"
    build:
      context: "./../backend"
      dockerfile: "./Dockerfile"
    env_file: .env
    ports:
      - 5050:5050
    volumes:
      - ../backend:/backend
      - /backend/node_modules
    command: npm run dev
