version: "3.8"

services:
  server:
    container_name: "pearn-server"
    build:
      context: "./../backend"
      dockerfile: "./Dockerfile"
    env_file: .env
    ports:
      - 5050:5050
    volumes:
      - ../backend:/backend
      - /backend/node_modules
    command: npm run dev
